name: deploy-api-to-vps

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  deploy-api-to-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push aftercinema-api Docker image into Docker Hub
        run: |
          cd api
          docker build -t gaspardcothiasfaure/aftercinema-api:1.1 .
          docker push gaspardcothiasfaure/aftercinema-api:1.1

      - name: Pull aftercinema-api Docker image and launch docker-compose.yml
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull gaspardcothiasfaure/aftercinema-api:1.1
            docker-compose -f /home/debian/lgna-sandbox/aftercinema/docker-compose.yml --env-file /home/debian/lgna-sandbox/aftercinema/.env up -d
