name: deploy-api-to-vps

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  deploy-api-to-vps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy files into VPS (1)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "api/app"
          target: "/home/debian/lgna-sandbox/aftercinema-api/app"
          rm: true
          strip_components: 2

      - name: Copy files into VPS (2)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "api/docker-compose.yml"
          target: "/home/debian/lgna-sandbox/aftercinema-api"
          overwrite: true
          strip_components: 1

      - name: Copy files into VPS (3)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "api/Dockerfile"
          target: "/home/debian/lgna-sandbox/aftercinema-api"
          overwrite: true
          strip_components: 1

      - name: Pull aftercinema-api Docker image and launch docker-compose.yml
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker build -t gaspardcothiasfaure/aftercinema-api:1.0 -f /home/debian/lgna-sandbox/aftercinema-api/Dockerfile /home/debian/lgna-sandbox/aftercinema-api
            docker push gaspardcothiasfaure/aftercinema-api:1.0
            docker-compose -f /home/debian/lgna-sandbox/aftercinema-api/docker-compose.yml --env-file /home/debian/lgna-sandbox/aftercinema-api/.env up -d
